# Generated by Django 5.0.6 on 2024-06-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=10)),
                ('feedback', models.CharField(max_length=30)),
            ],
        ),
    ]
