# Generated by Django 5.0.6 on 2024-06-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('coursename', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=10)),
                ('corsefee', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('certificate', models.CharField(max_length=20)),
            ],
        ),
    ]
